image: registry.gitlab.com/maketechnology/equo/docker/gradle:adoptopenjdk8-alpine

stages:
  - build
  - test
  - report
  - deploy

variables:
  GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle-home
  gradle_opt: "--build-cache --no-daemon"

# HOME is to cwd so bnd will download to ~/.bnd and ~/.m2 with ~=HOME
cache:
  key: "gradle"
  paths:
    - .gradle-home/
    - .m2/
    - .bnd/

before_script:
  - export HOME=$CI_PROJECT_DIR

.all:
  artifacts:
    reports:
       junit: 
          - "*/generated/test-reports/test/TEST-*.xml"
          - "*/generated/test-reports/testOSGi/TEST-*.xml"
    paths:
      - cnf/equoapp.bnd
      - cnf/equobuild.bnd
      - cnf/release
      - cnf/cache
      - cnf/build
      - build
      - build-cache
      - com.make.equo*/generated
    expire_in: 12w
    
.print_converage: &print_converage
- awk -F, '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, " instructions covered"; print 100*covered/instructions, "% covered" }' build/reports/jacoco/jacocoRootReport/jacocoRootReport.csv

build:
  extends: .all
  stage: build
  script:
    - gradle $gradle_opt assemble
  except:
    - master

test: 
  extends: .all
  stage: test
  script:
    - gradle $gradle_opt test
  except:
    - master
    
test.integration: 
  extends: .all
  image: registry.gitlab.com/maketechpub/docker/adopt:ubuntu.jdk8.gtk3
  stage: test
  before_script:
    - Xvfb :1 -screen 0 1152x720x24+32 -ac -noreset 2> xvfb.err &
    - export DISPLAY=:1
  script:
    - ./gradlew $gradle_opt testOSGi
  except:
    - master
    
    
coverage.report:
  extends: .all
  stage: report
  script:
    - gradle $gradle_opt jacocoRootReport
    - *print_converage
  except:
    - master
   

 

release:
  extends: .all
  stage: build
  script:
    - gradle jar
    - gradle check jacocoRootReport -PreportHtml=true
    - *print_converage
    - gradle release
    - gradle publish
  only:
    - master
    
pages:
  stage: deploy
  script:
    - cp -R $CI_PROJECT_DIR/build/reports/jacoco/jacocoRootReport/html/ public/
    - ls -R public/
  artifacts:
    paths:
    - public
  only:
    - master