image: us.gcr.io/equo-2018/win-adoptopenjdk8:latest

stages:
  - build

variables:
  GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle-home
  YARN_CACHE_FOLDER: $CI_PROJECT_DIR/.yarn-cache
  gradle_opt: "--build-cache --no-daemon"

# HOME is to cwd so bnd will download to ~/.bnd and ~/.m2 with ~=HOME
cache:
  key: "gradle"
  paths:
    - .yarn-cache/
    - .gradle-home/
    - .m2/
    - .bnd/


.all:
  artifacts:
    reports:
       junit:
          - "*/generated/test-reports/test/TEST-*.xml"
          - "*/generated/test-reports/testOSGi/TEST-*.xml"
    paths:
      - cnf/equoapp.bnd
      - cnf/equobuild.bnd
      - cnf/release
      - cnf/cache
      - cnf/build
      - build
      - build-cache
      - com.make.equo*/generated/*.jar
      - com.make.equo*/generated/jacoco/test.exec
    expire_in: 12w

build:
  extends: .all
  stage: build
  tags: [win]
  script:
    - ./gradlew --no-daemon assemble
