#!/bin/sh
# . "$(dirname "$0")/_/husky.sh"

# https://gist.github.com/rashtay/328da46a99a9d7c746636df1cf769675

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E "\.([jt]s|json)$")
ESLINT="$(git rev-parse --show-toplevel)/node_modules/.bin/eslint"

ESC="\033"
ESC_END="${ESC}[0m"
backgroundGreen="42"
backgroundLightGray="100"
backgroundRed="41"
bold="1"
green="32"
lightGray="90"
red="31"
underline="4"

validationCompleted() {
  printf "\n"
  printf "%b[%b;%bm┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓%b\n" "$ESC" "$bold" "$backgroundLightGray" "$ESC_END"
  printf "%b[%b;%bm┃                                                                              ┃%b\n" "$ESC" "$bold" "$backgroundLightGray" "$ESC_END"
  printf "%b[%b;%bm┃                      ¡Typescript validation completed!                       ┃%b\n" "$ESC" "$bold" "$backgroundLightGray" "$ESC_END"
  printf "%b[%b;%bm┃                                                                              ┃%b\n" "$ESC" "$bold" "$backgroundLightGray" "$ESC_END"
  printf "%b[%b;%bm┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛%b\n" "$ESC" "$bold" "$backgroundLightGray" "$ESC_END"
  printf "\n"
}

if [ -z "$STAGED_FILES" ]; then
  printf '\n	%b[%bmNo staged typescript, javascript and json files%b\n\n' "$ESC" "$underline" "$ESC_END"
  exit 0
fi

printf "\n %b[%bmStaged typescript, javascript and json files%b:\n" "$ESC" "$underline" "$ESC_END"

for FILE in $STAGED_FILES; do
  echo "	→ $FILE"
done

PASS=true

printf "\n %b[%bmValidating files%b:\n" "$ESC" "$underline" "$ESC_END"

# Check for eslint
if [ ! -x "$ESLINT" ]; then
  printf >&2 "	%b[%bmPlease install ESlint%b (\"yarn install\")\n" "$ESC" "$backgroundRed" "$ESC_END"
  exit 1
fi

for FILE in $STAGED_FILES; do
  "$ESLINT" "$FILE"

  if [ "$?" -eq 0 ]; then
    printf "	✅ %b[%b;%bmESLint Passed%b%b[%bm: %s%b\n" "$ESC" "$underline" "$green" "$ESC_END" "$ESC" "$green" "$FILE" "$ESC_END"
  else
    printf >&2 "	❌ %b[%b;%bmESLint Failed%b%b[%bm: %s%b\n" "$ESC" "$underline" "$red" "$ESC_END" "$ESC" "$red" "$FILE" "$ESC_END"
    PASS=false
  fi
done

validationCompleted

if ! $PASS; then
  printf >&2 "%b[%b;%bm  ¡COMMIT FAILED!  %b: Your commit contains files that should pass ESLint but do not. Please fix the ESLint errors (or try with %b[%bmyarn lint%b to automatically fix problems) and try again.\n\n" "$ESC" "$bold" "$backgroundRed" "$ESC_END" "$ESC" "$lightGray" "$ESC_END"
  exit 1
else
  printf "%b[%b;90;%bm  ¡COMMIT SUCCEEDED!  %b\n\n" "$ESC" "$bold" "$backgroundGreen" "$ESC_END"
fi

exit $?
